name: Build FreeRDP Windows x64
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      shell: powershell

    - name: Install Visual C++ Redistributable Packages via Chocolatey
      run: |
        choco install visualcpp-build-tools -y
        choco install vcbuildtools -y
        choco install vc-runtime -y
      shell: powershell

    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      shell: powershell

    - name: Configure and Build FreeRDP
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
        cmake --build . --config Release
      working-directory: ${{ github.workspace }}/FreeRDP

    - name: Create Artifact
      run: |
        mkdir artifacts
        cp build/Release/*.dll artifacts/
      working-directory: ${{ github.workspace }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: FreeRDP-Windows-x64
        path: artifacts/
